name: flutter_model_listview
description: An empowered ListView/GridView for Flutter with Load, Load more, Refresh and Error handling
version: 1.0.2
homepage: https://www.quantos.it

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_throttling: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
